image: docker:stable

stages:
- build
- test
- release

variables:
  TEST_IMAGE: $REPOSITORY_URL:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $REPOSITORY_URL:latest

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker pull $TEST_IMAGE

release:
  stage: release
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
    - aws ecs update-service --cluster Docker-Cluster --service Docker-Update2 --region us-east-1 --task-definition Release-port5k:1 --force-new-deployment
  only:
    - master
